Program from Arduino IDE (#394)

diff --git a/megaflash b/megaflash
--- a/megaflash
+++ b/megaflash
@@ -25,22 +25,23 @@ Example: ${0##*/} -v esp-link mysketch.hex
 EOT
 }
 
-if ! which curl >/dev/null; then
-  echo "ERROR: Cannot find curl: it is required for this script." >&2
+# ===== Find avrflash
+
+megaflash=$(readlink -e $0)
+avrflash=${megaflash%/*}/avrflash
+if [ ! -f $avrflash ]; then
+  echo "ERROR: Unable to find avrflash" >&2
   exit 1
 fi
-
-start=`date +%s`
 
 # ===== Parse arguments
 
 verbose=
 
-while getopts "hvx:" opt; do
+while getopts "hv" opt; do
   case "$opt" in
     h) show_help; exit 0 ;;
-    v) verbose=1 ;;
-    x) foo="$OPTARG" ;;
+    v) verbose='-v' ;;
     '?') show_help >&2; exit 1 ;;
   esac
 done
@@ -53,62 +54,7 @@ if [[ $# != 2 ]]; then
   show_help >&2
   exit 1
 fi
-hostname=$1
-hex=$2
 
-re='[-A-Za-z0-9.]+'
-if [[ ! "$hostname" =~ $re ]]; then
-  echo "ERROR: hostname ${hostname} is not a valid hostname or ip address" >&2
-  exit 1
-fi
+# ===== Run avrflash
 
-if [[ ! -r "$hex" ]]; then
-  echo "ERROR: cannot read hex file ($hex)" >&2
-  exit 1
-fi
-
-# ===== Get AVR in sync
-
-[[ -n "$verbose" ]] && echo "Resetting AVR with http://$hostname/pgmmega/sync" >&2
-v=; [[ -n "$verbose" ]] && v=-v
-sync=`curl -m 10 $v -s -w '%{http_code}' -XPOST "http://$hostname/pgmmega/sync"`
-if [[ $? != 0 || "$sync" != 204 ]]; then
-  echo "Error resetting AVR" >&2
-  exit 1
-fi
-
-while true; do
-  # sync=`curl -m 10 $v -s "http://$hostname/pgmmega/sync"`
-  sync=`curl $v -s "http://$hostname/pgmmega/sync"`
-  if [[ $? != 0 ]]; then
-    echo "Error checking sync" >&2
-    exit 1
-  fi
-  case "$sync" in
-  SYNC*)
-    echo "AVR in $sync"  >&2
-    break;;
-  "NOT READY"*)
-    [[ -n "$verbose" ]] && echo "  Waiting for sync..." >&2
-    ;;
-  *)
-    echo "Error checking sync: $sync" >&2
-    exit 1
-    ;;
-  esac
-  sleep 0.1
-done
-
-# ===== Send HEX file
-
-[[ -n "$verbose" ]] && echo "Sending HEX file for programming" >&2
-sync=`curl -m 20 $v -s -g -d "@$hex" "http://$hostname/pgmmega/upload"`
-echo $sync
-if [[ $? != 0 || ! "$sync" =~ ^Success ]]; then
-  echo "Error programming AVR" >&2
-  exit 1
-fi
-
-sec=$(( `date +%s` - $start ))
-echo "Success, took $sec seconds" >&2
-exit 0
+$avrflash -p atmega2560 $verbose $@
